spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecuritydemo?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: test